version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mbiz-quarkus-lambda-http-apis-jvm-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11xi5idigampf"
s3_prefix = "mbiz-quarkus-lambda-http-apis-jvm-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
